
app = "healthcare-app"
primary_region = "cdg"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  builder = "heroku/buildpacks:20"
